In [2]:
import sqlite3
import pandas as pd

In [4]:
conn = sqlite3.connect(r"C:\Users\samee\Downloads\1602668743_SQLFiles_Tier_1_updated_10_13_2020\SQLFiles Tier 1\sqlite_db_pythonsqlite.db")

In [5]:
df = pd.read_sql_query("SELECT * FROM Facilities;", conn)
df.head()

,facid,name,membercost,guestcost,initialoutlay,monthlymaintenance
0,0,Tennis Court 1,5.0,25.0,10000,200
1,1,Tennis Court 2,5.0,25.0,8000,200
2,2,Badminton Court,0.0,15.5,4000,50
3,3,Table Tennis,0.0,5.0,320,10
4,4,Massage Room 1,9.9,80.0,4000,3000

In [6]:
query = """
SELECT f.name,
       SUM(
           CASE 
               WHEN b.memid = 0 THEN b.slots * f.guestcost
               ELSE b.slots * f.membercost
           END
       ) AS revenue
FROM Bookings b
JOIN Facilities f ON b.facid = f.facid
GROUP BY f.name
HAVING revenue < 1000
ORDER BY revenue;
"""

df = pd.read_sql_query(query, conn)
df

            name  revenue
0   Table Tennis      180
1  Snooker Table      240
2     Pool Table      270

In [7]:
query = """
SELECT 
    m.surname || ', ' || m.firstname AS member_name,
    r.surname || ', ' || r.firstname AS recommender_name
FROM Members m
LEFT JOIN Members r 
    ON m.recommendedby = r.memid
ORDER BY m.surname, m.firstname;
"""

df = pd.read_sql_query(query, conn)
df

                 member_name    recommender_name
0            Bader, Florence    Stibbons, Ponder
1                Baker, Anne    Stibbons, Ponder
2             Baker, Timothy     Farrell, Jemima
3                Boothe, Tim         Rownam, Tim
4            Butters, Gerald       Smith, Darren
5               Coplin, Joan      Baker, Timothy
6             Crumpet, Erica        Smith, Tracy
7                Dare, Nancy    Joplette, Janice
8             Farrell, David                None
9            Farrell, Jemima                None
10              GUEST, GUEST                None
11          Genting, Matthew     Butters, Gerald
12                Hunt, John  Purview, Millicent
13              Jones, David    Joplette, Janice
14            Jones, Douglas        Jones, David
15          Joplette, Janice       Smith, Darren
16           Mackenzie, Anna       Smith, Darren
17             Owen, Charles       Smith, Darren
18             Pinker, David     Farrell, Jemima
19        Purview, Millicent        Smith, Tracy
20               Rownam, Tim                None
21         Rumney, Henrietta    Genting, Matthew
22         Sarwin, Ramnaresh     Bader, Florence
23             Smith, Darren                None
24             Smith, Darren                None
25               Smith, Jack       Smith, Darren
26              Smith, Tracy                None
27          Stibbons, Ponder       Tracy, Burton
28             Tracy, Burton                None
29      Tupperware, Hyacinth                None
30  Worthington-Smyth, Henry        Smith, Tracy

In [8]:
query = """
SELECT 
    f.name AS facility,
    COUNT(b.bookid) AS member_usage
FROM Bookings b
JOIN Facilities f ON b.facid = f.facid
WHERE b.memid != 0
GROUP BY f.name
ORDER BY member_usage DESC;
"""

df = pd.read_sql_query(query, conn)
df

          facility  member_usage
0       Pool Table           783
1    Snooker Table           421
2   Massage Room 1           421
3     Table Tennis           385
4  Badminton Court           344
5   Tennis Court 1           308
6   Tennis Court 2           276
7     Squash Court           195
8   Massage Room 2            27

In [9]:
query = """
SELECT 
    f.name AS facility,
    strftime('%m', b.starttime) AS month,
    COUNT(b.bookid) AS usage
FROM Bookings b
JOIN Facilities f ON b.facid = f.facid
WHERE b.memid != 0
GROUP BY f.name, month
ORDER BY f.name, month;
"""

df = pd.read_sql_query(query, conn)
df

           facility month  usage
0   Badminton Court    07     51
1   Badminton Court    08    132
2   Badminton Court    09    161
3    Massage Room 1    07     77
4    Massage Room 1    08    153
5    Massage Room 1    09    191
6    Massage Room 2    07      4
7    Massage Room 2    08      9
8    Massage Room 2    09     14
9        Pool Table    07    103
10       Pool Table    08    272
11       Pool Table    09    408
12    Snooker Table    07     68
13    Snooker Table    08    154
14    Snooker Table    09    199
15     Squash Court    07     23
16     Squash Court    08     85
17     Squash Court    09     87
18     Table Tennis    07     48
19     Table Tennis    08    143
20     Table Tennis    09    194
21   Tennis Court 1    07     65
22   Tennis Court 1    08    111
23   Tennis Court 1    09    132
24   Tennis Court 2    07     41
25   Tennis Court 2    08    109
26   Tennis Court 2    09    126